springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /company-service/v3/api-docs
        name: Company Service
      - url: /ticket-service/v3/api-docs
        name: Ticket Service