server:
  # port 번호가 0번이면 랜덤으로 배정된다.
  port: 0

spring:
  application:
    name: company-service
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        default_batch_fetch_size: 500
    open-in-view: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  profiles:
    include: s3, db, secret, oauth, swagger

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.example.companyservice.client: DEBUG

management:
  tracing:
    propagation:
      type: b3