server:
  port: 8761

spring:
  application:
    name: discovery-server
  cloud:
    openfeign:
      micrometer:
        enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka

# 로그에 traceId 추가
management:
  tracing:
    propagation:
      type: b3
